name: Automation Tests

on:
  push:
    branches:
      - dev

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20  

      - name: Install dependencies
        run: npm install

      - name: Run tests with Jest
        run: npm test # Add --coverage to generate test coverage report

      - name: Upload Jest Coverage Reports
        uses: actions/upload-artifact@v4.3.0
        if: always()
        with:
          name: test-reports
          path: coverage/Icov-report/index.html  # Specify the path where Jest stores coverage reports

      - name: Upload a jest test-report Artifact
        uses: actions/upload-artifact@v4.3.0
        with:
          name: jest-html-reporter
          path: newReport/test-report.html
          
      